// Word bank with hints for each round.
const WORDS = [
  { word: "apple", hint: "A crisp fruit often red or green" },
  { word: "bridge", hint: "A structure that spans a gap" },
  { word: "candle", hint: "Wax with a wick that gives light" },
  { word: "desert", hint: "A dry region with little rain" },
  { word: "eagle", hint: "A large bird of prey" },
  { word: "forest", hint: "A dense area of trees" },
  { word: "garden", hint: "A place where plants are grown" },
  { word: "harbor", hint: "A safe port for ships" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "jewel", hint: "A precious gem or ornament" },
  { word: "kettle", hint: "A pot used to boil water" },
  { word: "ladder", hint: "Rungs used for climbing" },
  { word: "melody", hint: "A sequence of musical notes" },
  { word: "needle", hint: "A thin tool used for sewing" },
  { word: "orange", hint: "A citrus fruit and a color" },
  { word: "palace", hint: "A grand royal residence" },
  { word: "quartz", hint: "A common crystalline mineral" },
  { word: "rocket", hint: "A vehicle that travels in space" },
  { word: "saddle", hint: "A seat placed on a horse" },
  { word: "temple", hint: "A place of worship" },
  { word: "umbrella", hint: "A handheld shield from rain" },
  { word: "valley", hint: "Low land between hills" },
  { word: "walnut", hint: "A hard-shelled edible nut" },
  { word: "xylophone", hint: "Percussion with tuned bars" },
  { word: "yacht", hint: "A sleek leisure boat" },
  { word: "zebra", hint: "Striped African animal" },
  { word: "anchor", hint: "A heavy device to hold a ship" },
  { word: "bakery", hint: "A shop that makes bread" },
  { word: "canyon", hint: "A deep gorge carved by a river" },
  { word: "diamond", hint: "A very hard precious stone" },
  { word: "engine", hint: "A machine that provides power" },
  { word: "feather", hint: "A light covering of a bird" },
  { word: "glacier", hint: "A slow-moving mass of ice" },
  { word: "hammer", hint: "A tool used to drive nails" },
  { word: "insect", hint: "A small creature with six legs" },
  { word: "jungle", hint: "A dense tropical forest" },
  { word: "kitten", hint: "A young cat" },
  { word: "lantern", hint: "A portable light with a handle" },
  { word: "marble", hint: "A smooth stone used in sculpture" },
  { word: "notebook", hint: "A book for notes" },
  { word: "orchard", hint: "A grove of fruit trees" },
  { word: "pillow", hint: "A soft cushion for sleep" },
  { word: "quarry", hint: "A site where stone is mined" },
  { word: "ribbon", hint: "A narrow strip used for tying" },
  { word: "sandwich", hint: "Food with filling between bread" },
  { word: "telescope", hint: "An instrument for viewing far objects" },
  { word: "uniform", hint: "Standard clothing for a group" },
  { word: "volcano", hint: "A mountain that can erupt" },
  { word: "window", hint: "An opening fitted with glass" },
  { word: "yogurt", hint: "A cultured dairy food" },
  { word: "zipper", hint: "A fastening with interlocking teeth" },
  { word: "artist", hint: "Someone who creates art" },
  { word: "blanket", hint: "A warm covering for a bed" },
  { word: "compass", hint: "A tool that shows direction" },
  { word: "dolphin", hint: "A smart marine mammal" },
  { word: "energy", hint: "Power used to do work" },
  { word: "farmer", hint: "A person who works the land" },
  { word: "galaxy", hint: "A vast system of stars" },
  { word: "helmet", hint: "Protective headgear" },
  { word: "igloo", hint: "A dome-shaped snow shelter" },
  { word: "jacket", hint: "Outerwear with sleeves" },
  { word: "kingdom", hint: "A realm ruled by a monarch" },
  { word: "lemon", hint: "A sour yellow citrus fruit" },
  { word: "magnet", hint: "An object that attracts iron" },
  { word: "number", hint: "A value used for counting" },
  { word: "ocean", hint: "A vast body of saltwater" },
  { word: "painter", hint: "Someone who makes pictures" },
  { word: "quill", hint: "A feather used as a pen" },
  { word: "river", hint: "A natural flowing waterway" },
  { word: "satellite", hint: "An object that orbits a planet" },
  { word: "thunder", hint: "The sound of a storm" },
  { word: "universe", hint: "All of space and everything in it" },
  { word: "vessel", hint: "A ship or large boat" },
  { word: "whisper", hint: "A very soft spoken sound" },
  { word: "yearbook", hint: "A school book of memories" },
  { word: "zenith", hint: "The highest point in the sky" },
  { word: "bicycle", hint: "A two-wheeled vehicle" },
  { word: "castle", hint: "A fortified stone residence" },
  { word: "dragon", hint: "A legendary fire-breathing creature" },
  { word: "elephant", hint: "The largest land mammal" },
  { word: "fountain", hint: "A decorative water feature" },
  { word: "guitar", hint: "A stringed musical instrument" },
  { word: "holiday", hint: "A special day of celebration" },
  { word: "iceberg", hint: "A floating mass of ice" },
  { word: "journey", hint: "A long trip" },
  { word: "kitchen", hint: "A room where food is cooked" },
  { word: "library", hint: "A place to borrow books" },
  { word: "mirror", hint: "A reflective surface" },
  { word: "nugget", hint: "A small lump of metal or food" },
  { word: "oxygen", hint: "A gas needed for breathing" },
  { word: "passport", hint: "An ID used for travel" },
  { word: "quilt", hint: "A stitched bed covering" },
  { word: "rainbow", hint: "A colorful arc in the sky" },
  { word: "science", hint: "The study of the natural world" },
  { word: "theater", hint: "A place for live performances" },
  { word: "utensil", hint: "A tool used for eating or cooking" },
  { word: "visitor", hint: "Someone who comes to see a place" },
  { word: "waterfall", hint: "A cascade where water drops" },
  { word: "meadow", hint: "A grassy open field" },
  { word: "harvest", hint: "The act of gathering crops" }
];
